"""
SatQuery AI — EMRDM Offline Inference Script
Run this on a GPU machine to produce precomputed reconstruction outputs.

Usage (GPU machine):
    cd /path/to/EMRDM
    pip install -r requirements.txt
    python /path/to/satquery-ai/scripts/run_emrdm_offline.py \\
        --input   /path/to/cloudy_input.png \\
        --mask    /path/to/cloud_mask.png \\
        --output  /path/to/SIH_26/data/demo/emrdm_demo_cloud_001/ \\
        --scene   emrdm_demo_cloud_001

After running, update data/demo/emrdm_demo_cloud_001/manifest.json with:
  - repository_commit
  - checkpoint + checkpoint_sha256
  - input_sha256
  - output_sha256
  - device (e.g. "NVIDIA A100 40GB")
  - execution_timestamp
  - runtime_seconds
  - precomputed: true

Then set SATQUERY_DEMO_DATA_DIR and the PrecomputedProvider will serve
the verified output automatically for that scene_id.

NOTE: Do NOT run this script on the demo machine (CPU only).
      It requires CUDA and PyTorch — neither installed in the main env.
"""

import argparse
import hashlib
import json
import os
import time
from pathlib import Path


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def run_emrdm(input_path: str, mask_path: str, output_dir: str, scene_id: str):
    """
    Run EMRDM inference and save output + update manifest.

    EMRDM repo: https://github.com/Ly403/EMRDM
    This function assumes EMRDM is cloned and importable.
    """
    output_dir_path = Path(output_dir)
    output_dir_path.mkdir(parents=True, exist_ok=True)

    manifest_path = output_dir_path / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"Manifest not found at {manifest_path}. "
            f"Expected a placeholder manifest generated by SatQuery data setup."
        )

    with open(manifest_path) as f:
        manifest = json.load(f)

    # --- EMRDM inference ---
    print(f"[EMRDM] Loading input: {input_path}")
    print(f"[EMRDM] Mask: {mask_path}")

    # Import EMRDM modules (only available on GPU machine)
    try:
        import torch
    except ImportError:
        raise RuntimeError(
            "PyTorch not installed. This script must run on a GPU machine "
            "with CUDA and PyTorch. The main SatQuery environment is CPU-only."
        )

    # --- Replace below with actual EMRDM inference code ---
    # import sys; sys.path.insert(0, '/path/to/EMRDM')
    # from emrdm.infer import run_inference
    # start = time.time()
    # output_image = run_inference(input_path, mask_path, checkpoint=CHECKPOINT_PATH)
    # elapsed = time.time() - start
    # output_image.save(output_path)
    # --- End EMRDM block ---

    raise NotImplementedError(
        "Replace the NotImplementedError block above with actual EMRDM inference code. "
        "See EMRDM repo: https://github.com/Ly403/EMRDM"
    )

    # After inference, record hashes
    output_filename = "reconstruction_output.png"
    output_path = str(output_dir_path / output_filename)
    input_sha = sha256_file(input_path)
    output_sha = sha256_file(output_path)

    import git
    try:
        repo = git.Repo(search_parent_directories=True)
        commit = repo.head.object.hexsha
    except Exception:
        commit = None

    manifest.update({
        "precomputed": True,
        "repository_commit": commit,
        "checkpoint": os.environ.get("EMRDM_CHECKPOINT", "unknown"),
        "input_sha256": input_sha,
        "output_filename": output_filename,
        "output_sha256": output_sha,
        "device": torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU",
        "execution_timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "runtime_seconds": elapsed,
    })

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"[EMRDM] Done. Output: {output_path}")
    print(f"[EMRDM] Manifest updated: {manifest_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run EMRDM offline inference")
    parser.add_argument("--input",  required=True, help="Path to cloudy input image")
    parser.add_argument("--mask",   required=True, help="Path to binary cloud mask")
    parser.add_argument("--output", required=True, help="Output directory (scene folder)")
    parser.add_argument("--scene",  required=True, help="Scene ID (must match manifest)")
    args = parser.parse_args()
    run_emrdm(args.input, args.mask, args.output, args.scene)
